version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: votingsystem_test
    volumes:
      - ./test_data/db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=postgresql://testuser:testpassword@database:5432/votingsystem_test
      - REDIS_URL=redis://redis:6379
      - FLASK_ENV=testing
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis

  verification-terminal:
    build:
      context: .
      dockerfile: Dockerfile.terminal
    environment:
      - BACKEND_URL=http://backend:5000
      - TERMINAL_ID=test-terminal-1
      - POLLING_STATION=test-station-1
      - AUTH_TOKEN=test-token-123
    depends_on:
      - backend 